openapi: 3.0.0
info:
  title: Hohma API
  description: API для хранения финальных результатов голосования за фильмы
  version: 1.0.0

components:
  schemas:
    FinalResults:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор результата
          example: "60d21b4667d0d8992e610c85"
        firstPlace:
          type: string
          format: uuid
          description: ID фильма, занявшего первое место
          example: "60d21b4667d0d8992e610c85"
        secondPlace:
          type: string
          format: uuid
          description: ID фильма, занявшего второе место
          example: "60d21b4667d0d8992e610c86"
        thirdPlace:
          type: string
          format: uuid
          description: ID фильма, занявшего третье место
          example: "60d21b4667d0d8992e610c87"
        date:
          type: string
          format: date-time
          description: Дата создания результата
          example: "2024-02-02T12:00:00Z"

paths:
  /api/final-results:
    get:
      summary: Получить все финальные результаты
      operationId: getAllFinalResults
      tags:
        - FinalResults
      responses:
        "200":
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FinalResults"
    post:
      summary: Добавить финальный результат
      operationId: addFinalResults
      tags:
        - FinalResults
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinalResults"
      responses:
        "201":
          description: Финальный результат успешно добавлен
        "400":
          description: Ошибка в данных запроса
